### ISSUE TITLE
NYPokecard

### ISSUE THREAD

**Issue by 1821698021** [carm-outsource/.github#2]
# 插件简介
插件名字: NYPokecard
服务器版本: 1.12.2
服务器核心: catserver

> 主要做一些宝可梦的小道具修改宝可梦的属性(只需要下面列出来的)：
> 梦特卡、闪光卡、移除闪光卡、满级卡、等级清空卡(改为1级)、性别卡、努力值卡、清空努力值卡、个体卡、全满个体卡、清空个体卡、性格卡、体型卡、形态卡、技能卡、改球类型卡、秒孵蛋卡

**其中这部分卡还需要做额外的随机性**
> 努力值卡、个体卡、性格卡、体型卡、形态卡、改球卡
> 简单来说就是选择宝可梦可以随机修改一项

# 配置需求
**道具我需要可以单独配置**
```yml
#我需要可以配置这些卡的道具外观
#比如：梦特卡
mt_card:
  material: paper
  #注意这里不是custommodel因为这是1.12的插件，这好像是那个损伤值，这样子的：155:1
  data: 0
  name: '&d无敌梦特卡'
  lore:
    - '可以把精灵改成梦特属性'
    - ''
    - '右键使用'
```
**黑名单配置，也就是说某些卡比如不能修改某些宝可梦或者一项数值**
>目前只需要做：梦特卡、个体卡、满值个体卡、形态卡即可
```yml
#形态卡举例
xt_card:
  blackList
    - '宝可梦名字@形态和数值'
    #这里就阻止玩家给鲤鱼王改form2形态
    - '鲤鱼王@form2'

#没有其他选项的就可以直接写名字
#个体卡举例
gt_card:
  blackList:
    - '鲤鱼王'


tell: 你不允许给%宝可梦名字%修改%形态变量%形态
tell: 你不允许给%宝可梦名字%修改个体
......
```

# 界面需求
**右键通常打开的界面，选择宝可梦，并且执行**
**slot中的123456为宝可梦图标展示，这个一般是锁死的我也不会修改它**
**具体格式内容见我发你的例子插件中config.yml文件最下面的lore行**
```yml
gui
  onlygui:
  #梦特卡界面
  mt_card:
    title: 梦特卡修改界面
    slot:
      - '########X'
      - '##1#2#3##'
      - '##4#5#6##'
    #一般放玻璃板装饰，和关闭界面的功能
    button:
      '#'
        材质: 玻璃板:子id
        名字: 我是装饰品
        lore: []
      'X'
        材质: 玻璃板:子id
        名字: 关闭界面
        lore: 
          - '点我即可关闭界面(不消耗卡)'
```
**第二层界面，通常有第二选择的时候的界面，有的卡需要有的卡就不需要，比如闪光卡只需要点击后进入第一界面点击宝可梦就完事了，但是有的卡比如个体卡点击后需要先选择宝可梦，然后再跳转到第二界面选择属性。**
```yml
#详细可以参考发你的插件gui.yml文件中的第386行以后的内容（或者直接搜索：anyGrowth）
```
